(defpackage #:http-kit/client
  (:use #:cl)
  (:import-from #:http-kit
                #:http-error
                #:http-protocol-error
                #:http-connection-error
                #:http-timeout
                #:http-size-limit-exceeded
                #:http-request
                #:http-request-p
                #:http-request-protocol-version
                #:http-request-method
                #:http-request-uri
                #:http-request-headers
                #:http-request-body
                #:http-response
                #:http-response-p
                #:http-response-protocol-version
                #:http-response-status
                #:http-response-reason
                #:http-response-headers
                #:http-response-trailers
                #:http-response-body
                #:http-unsupported-feature
                #:http-uri
                #:http-uri-p
                #:make-http-uri
                #:parse-http-uri
                #:http-uri-scheme
                #:http-uri-authority
                #:http-uri-host
                #:http-uri-port
                #:http-uri-path
                #:http-uri-query
                #:http-uri-string
                #:http-header
                #:http-header-p
                #:make-http-header
                #:http-header-name
                #:http-header-content
                #:http-header-values
                #:http-header-value
                #:http-header-present-p
                #:make-http-request
                #:make-http-response
                #:send-http-request-over-open-stream
                #:with-http-deadline
                #:send-http-request-over-stream)
  (:export
   ;; Client conditions
   #:http-client-error
   #:http-client-error-detail
   #:http-redirect-limit-exceeded
   #:http-redirect-limit-exceeded-uri
   #:http-redirect-limit-exceeded-redirects
   #:http-retry-exhausted
   #:http-retry-exhausted-attempts
   #:http-retry-exhausted-last-condition
   #:http-retry-exhausted-last-response
   #:http-cookie-error
   #:http-cache-error
   #:http-proxy-error
   ;; URI resolution and origin policy
   #:resolve-http-uri
   #:http-uri-origin
   #:http-same-origin-p
   ;; Encoding and entity construction
   #:http-percent-encode
   #:http-form-urlencode
   #:http-form-urlencoded-octets
   #:http-multipart-part
   #:http-multipart-part-p
   #:make-http-multipart-part
   #:http-multipart-part-name
   #:http-multipart-part-value
   #:http-multipart-part-filename
   #:http-multipart-part-content-type
   #:make-http-multipart-body
   #:parse-http-multipart-body
   ;; Server-sent events
   #:http-sse-event
   #:http-sse-event-p
   #:make-http-sse-event
   #:http-sse-event-event
   #:http-sse-event-data
   #:http-sse-event-id
   #:http-sse-event-retry
   #:http-sse-event-comments
   #:parse-http-sse-events
   #:read-http-sse-events
   #:serialize-http-sse-event
   ;; Cookies
   #:http-cookie
   #:make-http-cookie
   #:http-cookie-name
   #:http-cookie-value
   #:http-cookie-domain
   #:http-cookie-path
   #:http-cookie-expires
   #:http-cookie-max-age
   #:http-cookie-secure-p
   #:http-cookie-http-only-p
   #:http-cookie-same-site
   #:http-cookie-host-only-p
   #:http-cookie-creation-time
   #:http-cookie-jar
   #:make-http-cookie-jar
   #:http-cookie-jar-cookies
   #:http-cookie-jar-accept-response
   #:http-cookie-jar-cookie-header
   #:http-cookie-jar-clear
   ;; Policies
   #:http-redirect-policy
   #:make-http-redirect-policy
   #:http-redirect-policy-max-redirects
   #:http-redirect-policy-statuses
   #:http-redirect-policy-allow-downgrade-p
   #:http-redirect-policy-preserve-authorization-p
   #:http-retry-policy
   #:make-http-retry-policy
   #:http-retry-policy-max-attempts
   #:http-retry-policy-methods
   #:http-retry-policy-statuses
   #:http-retry-policy-base-delay
   #:http-retry-policy-max-delay
   #:http-retry-policy-respect-retry-after-p
   #:http-retry-policy-retry-on-timeout-p
   #:http-retry-policy-retry-on-connection-error-p
   ;; Date and authorization helpers
   #:http-parse-date
   #:http-basic-authorization
   #:http-bearer-authorization
   ;; Cache
   #:http-cache
   #:make-http-cache
   #:http-cache-entries
   #:http-cache-entry
   #:http-cache-entry-p
   #:http-cache-entry-key
   #:http-cache-entry-method
   #:http-cache-entry-uri
   #:http-cache-entry-response
   #:http-cache-entry-stored-at
   #:http-cache-entry-expires-at
   #:http-cache-entry-etag
   #:http-cache-entry-last-modified
   #:http-cache-entry-vary
   #:http-cache-entry-request-vary-values
   #:http-cache-entry-accessed-at
   #:http-cache-max-entries
   #:http-cache-clock-function
   #:http-cache-key
   #:http-cache-lookup
   #:http-cache-store
   #:http-cache-invalidate
   #:http-cache-clear
   ;; Proxy planning
   #:http-proxy
   #:make-http-proxy
   #:http-proxy-scheme
   #:http-proxy-host
   #:http-proxy-port
   #:http-proxy-username
   #:http-proxy-password
   #:http-proxy-no-proxy
   #:http-proxy-for-uri
   #:http-proxy-no-proxy-p
   #:http-proxy-plan
   #:make-http-proxy-stream-opener
   ;; Connection pooling
   #:http-connection-pool
   #:http-connection-pool-p
   #:make-http-connection-pool
   #:http-connection-pool-max-idle
   #:http-connection-pool-idle-timeout
   #:http-connection-pool-clock-function
   #:http-connection-pool-tls-upgrade
   #:http-connection-pool-resolve-host
   #:http-connection-pool-stats
   #:http-connection-pool-clear
   #:http-connection-pool-send
   ;; High-level client
   #:http-client
   #:http-client-p
   #:make-http-client
   #:http-client-transport-function
   #:http-client-connection-pool
   #:http-client-default-headers
   #:http-client-cookie-jar
   #:http-client-cache
   #:http-client-redirect-policy
   #:http-client-retry-policy
   #:http-client-proxy
   #:http-client-tls-upgrade
   #:http-client-resolve-host
   #:http-client-auth-provider
   #:http-client-clock-function
   #:http-client-wall-clock-function
   #:http-client-sleep-function
   #:http-client-max-header-bytes
   #:http-client-max-body-bytes
   #:http-client-on-request
   #:http-client-on-response
   #:http-client-request
   #:http-client-send))

(defpackage #:http-kit/websocket
  (:use #:cl)
  (:import-from #:http-kit
                #:http-protocol-error
                #:http-size-limit-exceeded
                #:http-request
                #:http-request-p
                #:http-request-protocol-version
                #:http-request-method
                #:http-request-headers
                #:http-response-p
                #:http-response-protocol-version
                #:http-response-status
                #:http-response-headers
                #:make-http-response
                #:http-header-p
                #:http-header-name
                #:http-header-values
                #:make-http-header
                #:make-http-request
                #:send-http-request-over-open-stream
                #:%monotonic-time)
  (:export
   #:websocket-frame
   #:websocket-frame-p
   #:websocket-frame-fin-p
   #:websocket-frame-opcode
   #:websocket-frame-mask-p
   #:websocket-frame-masking-key
   #:websocket-frame-payload
   #:make-websocket-frame
   #:serialize-websocket-frame
   #:parse-websocket-frame
   #:read-websocket-frame
   #:write-websocket-frame
   #:read-websocket-message
   #:write-websocket-message
   #:websocket-ping
   #:websocket-pong
   #:websocket-close
   #:serve-websocket-session
   #:websocket-accept-key
   #:websocket-upgrade-request-p
   #:websocket-upgrade-response
   #:make-websocket-upgrade-request
   #:websocket-client-handshake
   #:websocket-valid-close-code-p
   #:make-websocket-close-payload
   #:parse-websocket-close-payload))
