(defpackage #:http-kit/http3
  (:use #:cl)
  (:import-from #:http-kit
                #:http-invalid-header
                #:http-protocol-error
                #:http-size-limit-exceeded
                #:http-unsupported-feature)
  (:export
   #:+http3-data-type+
   #:+http3-headers-type+
   #:+http3-cancel-push-type+
   #:+http3-settings-type+
   #:+http3-push-promise-type+
   #:+http3-goaway-type+
   #:+http3-max-push-id-type+
   #:+http3-control-stream-type+
   #:+http3-qpack-encoder-stream-type+
   #:+http3-qpack-decoder-stream-type+
   #:+http3-setting-qpack-max-table-capacity+
   #:+http3-setting-enable-push+
   #:+http3-setting-max-field-section-size+
   #:+http3-setting-qpack-blocked-streams+
   #:+http3-setting-enable-connect+
   #:+http3-setting-h3-datagram+
   #:http3-varint-encode
   #:http3-varint-decode
   #:http3-frame
   #:http3-frame-p
   #:make-http3-frame
   #:http3-frame-type
   #:http3-frame-payload
   #:encode-http3-frame
   #:decode-http3-frames
   #:make-http3-settings-frame
   #:decode-http3-settings
   #:http3-control-state
   #:http3-control-state-p
   #:make-http3-control-state
   #:http3-control-state-settings-received-p
   #:http3-control-state-settings
   #:http3-control-state-goaway-id
   #:http3-control-state-max-push-id
   #:http3-control-state-cancelled-push-ids
   #:process-http3-control-frame
   #:process-http3-control-bytes
   #:http3-control-stream-prefix
   #:qpack-dynamic-entry
   #:qpack-dynamic-entry-p
   #:qpack-dynamic-entry-absolute-index
   #:qpack-dynamic-entry-name
   #:qpack-dynamic-entry-value
   #:qpack-dynamic-entry-size
   #:qpack-dynamic-table
   #:qpack-dynamic-table-p
   #:make-qpack-dynamic-table
   #:qpack-dynamic-table-max-capacity
   #:qpack-dynamic-table-capacity
   #:qpack-dynamic-table-entries
   #:qpack-dynamic-table-size
   #:qpack-dynamic-table-insert-count
   #:qpack-dynamic-table-set-capacity
   #:qpack-dynamic-table-insert
   #:qpack-encode-set-dynamic-table-capacity
   #:qpack-encode-insert-with-name-reference
   #:qpack-encode-insert-with-literal-name
   #:qpack-encode-duplicate
   #:qpack-encode-section-acknowledgment
   #:qpack-encode-stream-cancellation
   #:qpack-encode-insert-count-increment
   #:qpack-encode-field-section
   #:qpack-decode-field-section
   #:qpack-process-encoder-stream
   #:qpack-process-decoder-stream
   #:http3-client
   #:http3-client-p
   #:make-http3-client
   #:close-http3-client
   #:http3-client-open-p
   #:http3-client-open-stream
   #:http3-client-read-stream
   #:http3-client-write-stream
   #:http3-client-close-stream
   #:http3-client-peer-control-stream
   #:http3-client-peer-control-state
   #:http3-client-peer-control-prefix-seen-p
   #:http3-client-peer-control-fin-p
   #:http3-client-max-frame-size
   #:http3-client-max-header-bytes
   #:http3-client-qpack-settings
   #:attach-http3-peer-control-stream
   #:read-http3-control-stream
   #:serve-http3-control-stream
   #:send-http3-request
   #:send-http3-request/cps
   #:serve-http3-request-stream))
