(in-package #:http-kit/http3)

(defparameter +qpack-static-table+
  (vector
   (list ":authority" "")
   (list ":path" "/")
   (list "age" "0")
   (list "content-disposition" "")
   (list "content-length" "0")
   (list "cookie" "")
   (list "date" "")
   (list "etag" "")
   (list "if-modified-since" "")
   (list "if-none-match" "")
   (list "last-modified" "")
   (list "link" "")
   (list "location" "")
   (list "referer" "")
   (list "set-cookie" "")
   (list ":method" "CONNECT")
   (list ":method" "DELETE")
   (list ":method" "GET")
   (list ":method" "HEAD")
   (list ":method" "OPTIONS")
   (list ":method" "POST")
   (list ":method" "PUT")
   (list ":scheme" "http")
   (list ":scheme" "https")
   (list ":status" "103")
   (list ":status" "200")
   (list ":status" "304")
   (list ":status" "404")
   (list ":status" "503")
   (list "accept" "*/*")
   (list "accept" "application/dns-message")
   (list "accept-encoding" "gzip, deflate, br")
   (list "accept-ranges" "bytes")
   (list "access-control-allow-headers" "cache-control")
   (list "access-control-allow-headers" "content-type")
   (list "access-control-allow-origin" "*")
   (list "cache-control" "max-age=0")
   (list "cache-control" "max-age=2592000")
   (list "cache-control" "max-age=604800")
   (list "cache-control" "no-cache")
   (list "cache-control" "no-store")
   (list "cache-control" "public, max-age=31536000")
   (list "content-encoding" "br")
   (list "content-encoding" "gzip")
   (list "content-type" "application/dns-message")
   (list "content-type" "application/javascript")
   (list "content-type" "application/json")
   (list "content-type" "application/x-www-form-urlencoded")
   (list "content-type" "image/gif")
   (list "content-type" "image/jpeg")
   (list "content-type" "image/png")
   (list "content-type" "text/css")
   (list "content-type" "text/html; charset=utf-8")
   (list "content-type" "text/plain")
   (list "content-type" "text/plain;charset=utf-8")
   (list "range" "bytes=0-")
   (list "strict-transport-security" "max-age=31536000")
   (list "strict-transport-security" "max-age=31536000; includesubdomains")
   (list "strict-transport-security"
         "max-age=31536000;includesubdomains; preload")
   (list "vary" "accept-encoding")
   (list "vary" "origin")
   (list "x-content-type-options" "nosniff")
   (list "x-xss-protection" "1; mode=block")
   (list ":status" "100")
   (list ":status" "204")
   (list ":status" "206")
   (list ":status" "302")
   (list ":status" "400")
   (list ":status" "403")
   (list ":status" "421")
   (list ":status" "425")
   (list ":status" "500")
   (list "accept-language" "")
   (list "access-control-allow-credentials" "FALSE")
   (list "access-control-allow-credentials" "TRUE")
   (list "access-control-allow-headers" "*")
   (list "access-control-allow-methods" "get")
   (list "access-control-allow-methods" "get, post, options")
   (list "access-control-allow-methods" "options")
   (list "access-control-expose-headers" "content-length")
   (list "access-control-request-headers" "content-type")
   (list "access-control-request-method" "get")
   (list "access-control-request-method" "post")
   (list "alt-svc" "clear")
   (list "authorization" "")
   (list "content-security-policy"
         "script-src 'none'; object-src 'none'; base-uri 'none'")
   (list "early-data" "1")
   (list "expect-ct" "")
   (list "forwarded" "")
   (list "if-range" "")
   (list "origin" "")
   (list "purpose" "prefetch")
   (list "server" "")
   (list "timing-allow-origin" "*")
   (list "upgrade-insecure-requests" "1")
   (list "user-agent" "")
   (list "x-forwarded-for" "")
   (list "x-frame-options" "deny")
   (list "x-frame-options" "sameorigin")))
