(defpackage #:http-kit/http2
  (:use #:cl)
  (:import-from #:http-kit
                #:http-protocol-error
                #:http-invalid-header)
  (:export
   #:http2-client
   #:http2-client-p
   #:make-http2-client
   #:http2-client-connection
   #:http2-connection
   #:http2-connection-p
   #:make-http2-connection
   #:close-http2-connection
   #:cancel-http2-stream
   #:http2-connection-open-p
   #:http2-connection-session-started-p
   #:http2-connection-peer-max-frame-size
   #:http2-connection-peer-max-table-size
   #:http2-connection-peer-max-concurrent-streams
   #:http2-connection-peer-max-header-list-size
   #:http2-connection-peer-initial-window-size
   #:http2-connection-peer-connection-window-size
   #:http2-connection-goaway-last-stream-id
   #:http2-connection-local-goaway-last-stream-id
   #:http2-connection-draining-p
   #:http2-connection-manager
   #:http2-connection-manager-p
   #:make-http2-connection-manager
   #:close-http2-connection-manager
   #:http2-connection-manager-open-p
   #:http2-connection-manager-max-connections
   #:http2-connection-manager-idle-timeout
   #:http2-connection-manager-max-connection-age
   #:http2-connection-manager-clock-function
   #:http2-connection-manager-connection-count
   #:http2-connection-manager-connections
   #:send-http2-request-over-connection-manager
   #:send-http2-requests-over-connection-manager
   #:make-http2-connection-manager-transport
   #:make-http2-connection-transport
   #:ping-http2-connection
   #:send-http2-goaway
   #:send-http2-priority-update
   #:graceful-shutdown-http2-connection
   #:send-http2-request
   #:send-http2-request/cps
   #:send-http2-request-over-connection
   #:send-http2-request-over-connection/cps
   #:send-http2-requests-over-connection
   #:send-http2-requests-over-connection/cps
   #:serve-http2-session))
