(in-package #:http-kit)

(defun http-response-summary (response)
  (with-output-to-string (stream)
    (write-string (%response-protocol-version response) stream)
    (write-char #\Space stream)
    (write (%response-status response) :stream stream :escape nil)
    (write-char #\Space stream)
    (write-string (%response-reason response) stream)
    (write-string " headers=" stream)
    (write (length (%response-headers response)) :stream stream :escape nil)
    (write-string " trailers=" stream)
    (write (length (%response-trailers response)) :stream stream :escape nil)
    (write-string " body-bytes=" stream)
    (write (length (%response-body response)) :stream stream :escape nil)))
