(in-package #:http-kit)

(defun %join-octets (&rest vectors)
  (let ((result (make-array (reduce #'+ vectors :key #'length)
                            :element-type '(unsigned-byte 8)))
        (position 0))
    (dolist (vector vectors result)
      (replace result vector :start1 position)
      (incf position (length vector)))))

(defun %append-octet (vector octet)
  (let ((result (make-array (1+ (length vector))
                            :element-type '(unsigned-byte 8))))
    (replace result vector)
    (setf (aref result (length vector)) octet)
    result))

(defun %bounded-diagnostic (value &optional (limit 160))
  (let ((text (princ-to-string value)))
    (if (> (length text) limit)
        (concatenate 'string (subseq text 0 limit) "...")
        text)))
